stages:
  - deploy

variables:
  NETBOX_URL: "http://192.168.0.140:8000"
  NETBOX_TOKEN: "rDbitCHC2V3fQy2Ksmr1pRuagb7pCc2qXCYz7qEp"

deploy_to_production_auto:
  stage: deploy
  tags:
    - nornir
  script:
    - echo "🚀 Desplegando cambios BGP automáticamente desde NetBox..."
    - python3 apply_bgp_policies.py
  when: on_success
  # Elimina temporalmente la sección "only"
